th = input('Digite alguma coisa: ')
print('Tipo primitivo: ', type(th))
print(f'Eh numerico? {th.isnumeric()}')
print('Eh alfa? ', th.isalpha())
print('Eh alfanumerico? ', th.isalnum())
print('Ta em letra maiuscula?', th.isupper())
print('Ta em letra minuscula?', th.islower())
print('So tem espacos?', th.isspace())
print('Esta capitalizada?', th.istitle())
